ARG version
FROM almalinux:-9
ENV Name="sameer" \
    designation="DevOps Engineer" 
ARG experience=3
RUN echo "Name: $Name, Designation: $designation, Experience: $experience years"
CMD ["sleep", "1000"]